name: Deploy API Documentation

on:
  push:
    branches:
      - deploy-doc

permissions: read-all

concurrency:
  group: deploy-odoc
  cancel-in-progress: true

jobs:
  deploy-doc:
    name: Deploy odoc to GitHub Pages

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      id-token: write
      pages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.4.0
          dune-cache: true
          opam-pin: false

      - name: Pin packages
        run: |
          for f in *.opam; do
            opam pin add -yn "${f%.opam}" .
          done
        shell: bash

      - name: Install dependencies
        run: opam install . --deps-only --with-doc
        shell: bash

      - name: Build documentation
        run: opam exec -- dune build @doc
        shell: bash

      - name: Set-up Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/default/_doc/_html

      - name: Deploy odoc to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
